version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    environment:
      US_DB_USER: ${US_DB_USER}
      US_DB_HOST: ${US_DB_HOST}
      US_DB_NAME: ${US_DB_NAME}
      US_DB_PASS: ${US_DB_PASS}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      US_PORT: ${US_PORT}
    ports:
      - "3000:3000"
  admin-service:
    build:
      context: ./admin-service
    environment:
      US_DB_USER: ${US_DB_USER}
      US_DB_HOST: ${US_DB_HOST}
      US_DB_NAME: ${US_DB_NAME}
      US_DB_PASS: ${US_DB_PASS}
      NS_DB_USER: ${NS_DB_USER}
      NS_DB_HOST: ${NS_DB_HOST}
      NS_DB_NAME: ${NS_DB_NAME}
      NS_DB_PASS: ${NS_DB_PASS}
      JWT_SECRET: ${JWT_SECRET}
      NS_PORT: ${NS_PORT}
    ports:
      - "3001:3001"
